---
settings:
  name: Ransomware Protection
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: fr-fr,us-en,ja-jp,zh-cn,zh-tw,ko-kr,de-de
sidebar:
  entries:
  - title: Documents sur la protection des ransomwares
    url: "/index.html"
  - title: Notes de mise à jour
    url: "/whats-new.html"
  - title: Commencez
    entries:
    - title: Découvrez la protection contre les ransomwares
      url: "/concept-ransomware-protection.html"
    - title: Surveillance des alertes par ransomware dans le Centre de notification
      url: "/task-monitor-ransomware-alerts.html"
  - title: Protection contre les ransomwares
    entries:
    - title: Gérez les recommandations en matière de cybersécurité pour vos données
      url: "/task-analyze-ransomware-data.html"
  - title: Connaissances et support
    entries:
    - title: S'inscrire pour obtenir de l'aide
      url: "/task-support-registration.html"
    - title: Obtenez de l'aide
      url: "/task-get-help.html"
  - title: Mentions légales
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: Commencez
    links:
    - title: Découvrez la protection contre les ransomwares
      url: concept-ransomware-protection.html
    - title: Nouveautés
      url: whats-new.html
  - title: Gérez les recommandations en matière de cybersécurité
    links:
    - title: Affichez les principaux référentiels de données en fonction de la sensibilité
        des données
      url: task-analyze-ransomware-data.html#top-data-repositories-by-data-sensitivity
    - title: Afficher les utilisateurs qui ont été ajoutés aux groupes d'administrateurs
        de domaine
      url: task-analyze-ransomware-data.html#domain-administrator-group-control
    - title: Afficher les données répertoriées par les autorisations ouvertes
      url: task-analyze-ransomware-data.html#data-listed-by-types-of-open-permissions
    - title: Afficher les données répertoriées par les fichiers chiffrés
      url: task-analyze-ransomware-data.html#data-listed-by-encrypted-files
    - title: Découvrez comment protéger vos systèmes ONTAP contre les attaques par
        ransomware de façon sécurisée
      url: task-analyze-ransomware-data.html#status-of-ontap-systems-hardening
  - title: Communauté sur les blogs
    links:
    - title: Communauté NetApp
      url: https://community.netapp.com/t5/Cloud-Data-Services/ct-p/CDS
    - title: Blog BlueXP
      url: https://cloud.netapp.com/blog
    - title: Webinaires sur le cloud
      url: https://cloud.netapp.com/events
product-family:
  name: BlueXP
  repo: cloud-manager-family
  sidebar_label: Toute la documentation BlueXP
